// Package secrets manage the local LLM API key placement (without entering yaml or warehouse).
package secrets

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/toninfo/ton/internal/brand"
)

const envFileName = "llm.env"

// ConfigDirEnv configuration directory coverage variable (TON_CONFIG_DIR); testing can set this isolation.
const ConfigDirEnv = "TON_CONFIG_DIR"

// Dir returns the configuration directory (including llm.env / config.yaml).
func Dir() string {
	return brand.ResolveConfigDir()
}

// FilePath returns the key file path: <config dir>/llm.env
func FilePath() string {
	return filepath.Join(Dir(), envFileName)
}

// LoadAPIKey reads TON_LLM_API_KEY from a key file.
func LoadAPIKey() (string, error) {
	path := FilePath()
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	defer f.Close()
	primary := brand.EnvKey("LLM_API_KEY")
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, primary+"=") {
			return strings.TrimSpace(strings.TrimPrefix(line, primary+"=")), nil
		}
	}
	return "", sc.Err()
}

// SaveAPIKey writes the key file and chmod 600; also Setenv to the current process.
func SaveAPIKey(key string) error {
	key = strings.TrimSpace(key)
	if key == "" {
		return fmt.Errorf("secrets: empty API key")
	}
	path := FilePath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	primary := brand.EnvKey("LLM_API_KEY")
	content := "# Generated by " + brand.Name + " /key — do not commit\n" + primary + "=" + key + "\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return err
	}
	return os.Setenv(primary, key)
}
