// Package secrets 管理本机 LLM API key 落盘（不进 yaml、不进仓库）。
package secrets

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/toninfo/ton/internal/brand"
)

const envFileName = "llm.env"

// ConfigDirEnv 配置目录覆盖变量（TON_CONFIG_DIR）；测试可设此隔离。
const ConfigDirEnv = "TON_CONFIG_DIR"

// Dir 返回配置目录（含 llm.env / config.yaml）。
func Dir() string {
	return brand.ResolveConfigDir()
}

// FilePath 返回密钥文件路径：<config dir>/llm.env
func FilePath() string {
	return filepath.Join(Dir(), envFileName)
}

// LoadAPIKey 从密钥文件读取 TON_LLM_API_KEY。
func LoadAPIKey() (string, error) {
	path := FilePath()
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	defer f.Close()
	primary := brand.EnvKey("LLM_API_KEY")
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, primary+"=") {
			return strings.TrimSpace(strings.TrimPrefix(line, primary+"=")), nil
		}
	}
	return "", sc.Err()
}

// SaveAPIKey 写入密钥文件并 chmod 600；同时 Setenv 到当前进程。
func SaveAPIKey(key string) error {
	key = strings.TrimSpace(key)
	if key == "" {
		return fmt.Errorf("secrets: empty API key")
	}
	path := FilePath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	primary := brand.EnvKey("LLM_API_KEY")
	content := "# Generated by " + brand.Name + " /key — do not commit\n" + primary + "=" + key + "\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return err
	}
	return os.Setenv(primary, key)
}
